---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    config:
      extensions:
      - .vue
      - .js
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.module"
  - "**.vue"
exclude_paths:
  - config/
  - build/
  - cordova/
  - static/
