version: '2'
services:
  web:
    build: .
    command: 'npm run dev'
    volumes:
      - carpoolear-sync:/myapp:nocopy
    ports:
      - "8080:8080"
  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:z
  #     - carpoolear-sync:/myapp:nocopy
  #   ports:
  #     - "80:80"
  #   expose:
  #     - "80"
  #   # volumes_from:
  #   #  - web
  #   depends_on:
  #     - web
volumes:
  carpoolear-sync:
    external: true
